org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
android.useAndroidX=true
kotlin.code.style=official
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

android.nonTransitiveRClass=true
android.nonFinalResIds=false

android.experimental.enableScreenshotTest=true

kotlin.native.binary.gc=cms
kotlin.incremental.wasm=true

org.jetbrains.compose.experimental.jscanvas.enabled=true
android.builtInKotlin=false
android.newDsl=false
