org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

android.experimental.enableScreenshotTest=true
android.nonFinalResIds=true
android.builtInKotlin=true
android.newDsl=true

kotlin.native.binary.gc=cms
kotlin.incremental.wasm=true
org.jetbrains.compose.experimental.jscanvas.enabled=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
