name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
          fetch-depth: 0

    - name: set up JDK 21
      uses: actions/setup-java@v6.0.0
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Gradle Setup
      uses: gradle/actions/setup-gradle@v6
      with:
        cache-cleanup: on-success
        cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

    - name: Test App Gradle
      run: make testApp
    - name: Build App Gradle
      run: make buildApp
    - name: Screenshot Test
      run: make screenshotTest
    - name: Build Wear Gradle
      run: make buildWear
