name: KMMBridge Publish Release
on: workflow_dispatch

jobs:
    call-kmmbridge-publish:
        uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v1.1
        secrets:
            PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}



