# Simple workflow for deploying static content to Cloudflare Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployments
permissions:
  contents: read
  deployments: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'
      - name: Build Web
        run: make buildWeb
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: 'cmp-common/build/dist/composeWebCompatibility/productionExecutable'
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy cmp-common/build/dist/composeWebCompatibility/productionExecutable --project-name=coffeegram
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ github.token }}
